### ISSUE TITLE
Alienware 13 R3 Bios 1.18.0 not working with AMD Radeon RX 6600

### ISSUE THREAD

**Issue by yitelu** [Shidell/OpenCaldera#12]
Hi,

Thanks for your OpenCaldera project, but unfortunately that didn't work on my AMD RX 6600 with AW 13 R3

AW laptop: Alienware 13 R3 Bios v1.18.0 on Win10 22H2
Graphics card: AMD Radeon RX 6600 (brand new)

- [x] Checked all the windows updates and drivers are latest.
- [x] Checked that graphics card didn't power up and gpu fan didn't spin when I turn the laptop on
- [x] Confirmed GPU RX6600 not recognized in the Device Manager that no new GPU RX6600 show up
- [x] Tried the HackFlags 200/400/600 but none of them is working for my rig.
- [x] Tried the OpenCaldera 0.1.1.0 still not working for my rig.

#---------------------------------------------------
OpenCaldera 0.1.1.0

Reading Alienware Graphics Amplifier BIOS Properties:
Is Present:                     False
Is Connected:                   True
Is Card Type Supported:         False
Is Restart Pending:             False
Is Undock Request Set:          False
Is Surprise Removal Set:        False
MState:                         M3
Press Enter to close.

Attached the AW DLL files from my end for your reference: 
[AWGA_DLL.zip](https://github.com/Shidell/OpenCaldera/files/10088143/AWGA_DLL.zip)
#--------------------------------------------------

I saw your post about you got RX6800 working during 2020, but maybe the AW Bios update in 2022 that changed everything.

I'll give a one more shot on the "AW official support nVidia RTX2070" and hope that would work

Thanks

**Comment by Shidell** [comment]
So, to be sure, the RX 6600 powers up when you turn the laptop on?

Do you have any other desktop GPU you could test with in the AGA, even if older? Do you have another computer you can test the RX 6600 in to verify it's working?

**Comment by yitelu** [comment]
the RX 6600 powers up when you turn the laptop on? -> **No, RX6600 fan didn't turn on, no fan spinning and didn't pick up any device in window's device manager.**

Do you have any other desktop GPU you could test with in the AGA, even if older? -> **I've tried the nVidia GTX1650 in AGA and gtx1650 worked with AGA smoothly without any issue.**

Do you have another computer you can test the RX 6600 in to verify it's working? -> **yep RX6600 is brand new and it's fully working in any PC without the AGA.**

Following are the method that I've tried:
- [x] Tried roll-back the AW13R3 Bios 1.18.0~1.10.0 but none of the that worked 
- [x] Tried AW13R3 on Win11 and no luck as well

My conclusion:
- [x] AMD RX6600 in AGA won't work with "my" AW13R3.
- [x] Suggest don't waste more time to hack around to make RX6600 compatible with AW laptop & AGA that's already an antique machine (intel i7 7700HQ)
- [x] Just buy 2nd hand Geforce GTX1080Ti that perform better than RX6600 for similar price range $200~$250 USD.
- [x] or go for RTX2080Ti that's the highest card nvidia official support in AGA. ($400~450 USD range)
- [x] whoever saw this post, it would save you at least 2 days of digging in the rabbit hole! you're welcome :)

**Comment by Shidell** [comment]
@yitelu  Hm, that's odd behavior. The 6600 should, at minimum, light up and the fans should spin when you power on your laptop. The fact that it does not implies that it's not receiving power--or not receiving enough power--to operate properly. But, that's also weird, as the RX 6600 should only draw 132W, using a single 8-pin connector. I don't see why the GTX 1650 would work, but the RX 6600 would not. 

1. What make/model is your 6600?
2. Is it possible it was not seated properly/fully in the AGA?
3. Is it possible you forgot to connect the 8-pin power adapter from the PSU while you were testing?

This is the first account of a Radeon (any Radeon) not working in the AGA, that I'm aware of. There are only two Nvidia vendors who are problematic in the AGA; Zotac is notorious for not working, and so are OEM vendors (like a Dell-branded GeForce.) I suspect that if none of the above are a factor in your 6600, it might actually be a vendor firmware problem.

Finally, if you have confirmed it was fully seated and power was connected (might be worth trying again!), I'd encourage you to check the vendor's website to see if there is an updated firmware for the 6600; you could flash that via your desktop.

**Comment by yitelu** [comment]
What make/model is your 6600? -> MSI
Is it possible it was not seated properly/fully in the AGA? -> no, it's the same installation method as Nvidia GTX1650 that proof i know how to install it properly.
Is it possible you forgot to connect the 8-pin power adapter from the PSU while you were testing? -> I wish it was that easy but no.

Btw the firmware in rx6600 is already the latest, anyway I've completely give up on Radeon RX6600 won't invest more time. Besides Dell/AW has already completely abandon AGA forever, so there's no point waste time to hack around.

Anyone who fall into the rabbit hole like i did, i would simply suggest you instead of buy Rx6600 (not in the AGA compatible list) with AGA, just buy the 2nd hand Geforce GTX1080Ti (in the AGA compatible list) that perform way better than RX6600 for the similar price range of $200~$250 USD on Nov/2022

[Official Alienware Graphics Amplifier: Supported Graphics Card List](https://www.dell.com/support/kbdoc/en-us/000178406/alienware-graphics-amplifier-supported-graphics-card-list)

thanks and ticket closed.
