### ISSUE TITLE
no Graphics Amplifier folder

### ISSUE THREAD

**Issue by brycenoland** [Shidell/OpenCaldera#3]
I have AGA successfully running with RTX 2080 TI, but I don't have the Alienware\Graphics Amplifier in program files or program files(x86) directories.  The GraphicsAmplifier.Domain.dll and GraphicsAmplifierServiceController.exe exists in C:\Program Files\Alienware\Alienware Command Center on my system.

**Comment by Shidell** [comment]
Thanks! I'll work on an update to probe those directories by default as well. In the meantime, if you copy OpenCaldera.exe into C:\Program Files\Alienware\Alienware Command Center, it should discover those libraries automatically and run as expected. Can you verify?

**Comment by brycenoland** [comment]
I tried it in the Alienware Command Center dir, but it still wouldn't work...I made some code changes and compiled it myself and posted my output.

**Comment by Shidell** [comment]
This should be corrected as of the 0.1.1.0 build.
