### ISSUE TITLE
Asus tuf rx6800xt does not turn on with AGA

### ISSUE THREAD

**Issue by xD3XT3Rx** [Shidell/OpenCaldera#9]
Hello, excuse me, my English, I only speak Spanish.
I have been trying to solve my problem for days I have read hundreds of forums even without a solution, I have a graphics amplifier that I bought new on ebay, the model is z01g and I have a laptop alienware area 51m R2 core i7 10700 ram 2933 bios capped I do not have access to options advanced. when i connect the amplifier with a gtx 1660 or nvidia card the amplifier works as it should. you turn on the cable and it is detected in the task manager. so i decided to buy an asus tuf rx6800xt but it was disappointing to learn that it doesn't work with my graphics amp. the graphics card does not turn on and the cable does not turn on. the graphics amplifier does not detect the amd card, only the usb ports work. if the card does not turn on there is no way for the task manager to detect it. AGA works for others with the rx6800xt. I don't know what happens. No solution from this forum or from other forums has worked for me. I attach 2 videos where I teach the operation of the aga with nvidia and amd.

Nvidia video card running AGA
https://drive.google.com/file/d/1x06ymzvxu2vDUrQNe5q2HOqESbQzjLhy/view?usp=drivesdk

AMD video card not detected by AGA
https://drive.google.com/file/d/1Zmjo8WO6ri-D9U92H8IhE3erHHF3H1HK/view?usp=drivesdk

the rx6800xt was tested on another system and it works perfectly. I need help. the AGA refuses to turn on my 6800xt
Thank you

**Comment by Shidell** [comment]
@xD3XT3Rx I apologize, I don't speak Spanish, so I hope a response in English is helpful. (For what it's worth, your English is pretty good.)

Your Area-51M R2 should work correctly with the RX 6800 XT. As connected right now, do you have a Device Bang (Yellow Exclamation Point) in the Device Manager under "System" when booting with the 6800 XT attached?

I think you need to enable "HackFlags" (200) in the Registry, then restart your computer, in order to fix your problem. Please see this more detailed post I created on reddit: https://www.reddit.com/r/Alienware/comments/nk718z/the_state_of_the_alienware_graphics_amplifier_in/

Also, after you install the AMD drivers and the GPU is detected and working properly, make sure when you boot up that you have an "AMD XConnect" icon in the task bar, by your WiFi/Internet, Sound, Power, etc. options. If you do not, an AMD GPU in the AGA will not work properly (at full speed); I've found that I need to power off fully, then power on, in order for it to work properly. If I reboot, it gets messed up—so keep in mind that you may need to power down fully and then power back on when you reboot to make sure it gets detected properly.

**Comment by xD3XT3Rx** [comment]
> @xD3XT3Rx I apologize, I don't speak Spanish, so I hope a response in English is helpful. (For what it's worth, your English is pretty good.)
> 
> Your Area-51M R2 should work correctly with the RX 6800 XT. As connected right now, do you have a Device Bang (Yellow Exclamation Point) in the Device Manager under "System" when booting with the 6800 XT attached?
> 
> I think you need to enable "HackFlags" (200) in the Registry, then restart your computer, in order to fix your problem. Please see this more detailed post I created on reddit: https://www.reddit.com/r/Alienware/comments/nk718z/the_state_of_the_alienware_graphics_amplifier_in/
> 
> Also, after you install the AMD drivers and the GPU is detected and working properly, make sure when you boot up that you have an "AMD XConnect" icon in the task bar, by your WiFi/Internet, Sound, Power, etc. options. If you do not, an AMD GPU in the AGA will not work properly (at full speed); I've found that I need to power off fully, then power on, in order for it to work properly. If I reboot, it gets messed up—so keep in mind that you may need to power down fully and then power back on when you reboot to make sure it gets detected properly.

hi thanks for your help, but this is not working for me. I already problem this before without success. I think it is the solution for those who have the yellow symbol in the task manager. but I don't have a yellow symbol. the 6800xt is not detected anywhere. This failure is strange, it works for others but not for me. after analyzing the operation of the AGA this turns on the card when windows is starting. in my case the card is dead. I also tried a 6600xt without success. for now it only works with nvidia cards. maybe it's a bios problem in the AGA? when I try to install the amd drivers it throws an error that it cannot find compatible devices. there are no yellow symbols in the task manager. Will tuf 6800xt be AGA compliant? I have seen a merc 6800xt work with AGA I don't know. maybe the bios version of my AGA is the problem? I don't know I've already tried everything. refuses to turn on AMD 6000 cards ...

**Comment by xD3XT3Rx** [comment]
> @xD3XT3Rx I apologize, I don't speak Spanish, so I hope a response in English is helpful. (For what it's worth, your English is pretty good.)
> 
> Your Area-51M R2 should work correctly with the RX 6800 XT. As connected right now, do you have a Device Bang (Yellow Exclamation Point) in the Device Manager under "System" when booting with the 6800 XT attached?
> 
> I think you need to enable "HackFlags" (200) in the Registry, then restart your computer, in order to fix your problem. Please see this more detailed post I created on reddit: https://www.reddit.com/r/Alienware/comments/nk718z/the_state_of_the_alienware_graphics_amplifier_in/
> 
> Also, after you install the AMD drivers and the GPU is detected and working properly, make sure when you boot up that you have an "AMD XConnect" icon in the task bar, by your WiFi/Internet, Sound, Power, etc. options. If you do not, an AMD GPU in the AGA will not work properly (at full speed); I've found that I need to power off fully, then power on, in order for it to work properly. If I reboot, it gets messed up—so keep in mind that you may need to power down fully and then power back on when you reboot to make sure it gets detected properly.

hi thanks for your help, but this is not working for me. I tried this before without success. I think it is the solution for those who have the yellow symbol in the task manager. but I don't have a yellow symbol. the 6800xt is not detected anywhere. This failure is strange, it works for others but not for me. after analyzing the operation of the AGA this turns on the card when windows is starting. in my case the card is dead. I also tried a 6600xt without success. for now it only works with nvidia cards. maybe it's a bios problem in the AGA? when I try to install the amd drivers it throws an error that it cannot find compatible devices. there are no yellow symbols in the task manager. Will tuf 6800xt be AGA compliant? I have seen a merc 6800xt work with AGA I don't know. maybe the bios version of my AGA is the problem? I don't know I've already tried everything. refuses to turn on AMD 6000 cards ...

**Comment by Shidell** [comment]
It "should" work; I haven't encountered anyone where this hasn't worked, albeit some have required more effort to figure out the reason why.

Is your 51M R2 running the latest firmware, 1.10.0?

Are you running Windows 11?

Do you have the latest Intel Chipset INF drivers installed?

It could also be, that for whatever reason, your PSU isn't able to supply enough power to the 6800 XT to allow it to start up properly. The stock PSU supplies up to 460w, which should be enough, but parts can/do fail, including simply getting weaker and/or not providing the expected power. Do you have a spare PSU you could connect to the AGA temporarily? You don't need to fully install it; just connect it to the AGA motherboard and the GPU.

**Comment by xD3XT3Rx** [comment]
I am using windows 10 the bios is updated to the latest version. the AGA ran today with an rtx2080ti that I borrowed from a friend to test. I tried an 850w source with no success on my 6800xt. the AGA does not turn on the 6800xt and 6600xt but with nvidia it works fine. I am frustrated with this. I think it is something in the bios that prevents the AGA from turning on the 6000 series cards. I've been with this for several days without a solution. I want the AGA but if I do not solve this I will have to buy a razer core x and accept less performance

**Comment by Shidell** [comment]
Is there perhaps a different (updated?) firmware for the RX 6800 XT you have?

This would be the first system I've encountered that simply is not/does not work, so I suspect there's something else going on that's causing it to not work, aside from a general inability to do so.
